version: 0.2

env:
  variables:
    CAHE_CONTROL: "86400"
    S_BUCKET: "{{s3_bucket_url}}"
    BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo installing source NPM dependencies
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo building application
      - ng build
  artifacts:
    files:
      - "**/*"
    base-directory: "dist*"
    discard-paths: yes